server.port: 8080

solon.app:
  name: 'demo-app'
  group: 'demo'

demo.db1:
  schema: rock
  jdbcUrl: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

# 配置数据源对应的 mybatis 信息（要与 DataSource bean 的名字对上）
mybatis.db1:
  configuration: #扩展配置（要与 MybatisConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapperVerifyEnabled: false #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true
  globalConfig: #全局配置（要与 GlobalConfig 类的属性一一对应）
    banner: false

# warm-flow工作流配置
warm-flow:
  # 是否显示banner图，默认是
  banner: true
  # 填充器 （可配置文件注入，也可用@Bean/@Component方式）
  #  data-fill-handler-path: com.warm.flow.core.test.handle.CustomDataFillHandler
  # 全局租户处理器（可配置文件注入，也可用@Bean/@Component方式）
  #  tenant_handler_path: com.warm.flow.core.test.handle.CustomTenantHandler
  # 是否开启逻辑删除
  logic_delete: false
  # 逻辑删除字段值（开启后默认为2）
  logic_delete_value: 2
  # 逻辑未删除字段（开启后默认为0）
  logic_not_delete_value: 0

# warm-flow-jpa 的hibernate jpa配置 此处属于固定配置
warm-flow-jpa:
# jpa 与 数据源绑定，此处填写数据源名称
  datasource: db1
# hibernate 配置配置
  properties:
    hibernate:
      hbm2ddl:
        auto: none
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      connection:
        isolaction: 4 # 事务隔离级别 4 可重复度
